#!/bin/bash
# Run the grace_ou_6M.slurm array on a local workstation instead of Grace.
#
#     bash hpc/run_array_local.sh                  # tasks 1-20, 4 workers
#     bash hpc/run_array_local.sh -a 3-20          # just tasks 3..20
#     bash hpc/run_array_local.sh -n 2 -s 200000   # 2 workers, short test runs
#     bash hpc/run_array_local.sh --dry-run
#
# Mirrors grace_ou_6M.slurm exactly -- same seeds (20260930 + task), same flags
# (--continuous --batch 1 --start-at-rest --traj-interval 200), same per-task
# HOMEO_DATA_DIR and NUMBA_CACHE_DIR -- so the output is directly comparable
# with a Grace array and `aggregate_array.py` reads it unchanged.
#
# Why this exists: an expired allocation, or anything else that makes Grace
# unavailable. Grace is still the better venue -- there all 20 tasks run on 20
# separate cores and the array finishes in one run's wall time (~37 min),
# whereas locally they queue through however many cores you have.
#
# Measured on a 4-core Xeon W-2123: 2774 steps/s solo, so ~36 min per 6M-step
# run; 4 concurrent runs slow each other by ~1.25x, giving ~45 min per run and
# ~3.7 h for the full 20. Re-measure with `-n 1 -s 200000` on other hardware.
#
# Re-runnable: a task whose batch CSV already exists is skipped, so an
# interrupted batch can be resumed by invoking the same command with -o
# pointing at the existing run directory.
#
# SPLITTING ACROSS TWO MACHINES.  The tasks are independent and seeded purely by
# index, so a split is exact: the union of two partial runs is the same 20 runs
# one machine would have produced.  Give each machine a disjoint range, then
# merge the task_* directories and aggregate as usual.  Divide the ranges in
# proportion to measured throughput, and remember a machine finishes in whole
# waves of <workers> tasks, so a range that straddles a wave boundary buys
# nothing.  Example with a 4-core workstation (~45 min/task when 4 run at once)
# and a slower 4-core server (~53 min/task):
#
#     RUN=.../SimulationsData/ou6M-2026-10-01
#     # the faster machine takes 12, i.e. 3 waves:
#     bash hpc/run_array_local.sh -a 1-12 -o "$RUN"
#     # the slower one takes 8, i.e. 2 waves (PYTHON= if its venv is elsewhere):
#     ssh server 'cd ~/Homeo && PYTHON=$HOME/homeo-venv/bin/python \
#         nohup bash hpc/run_array_local.sh -a 13-20 -o $HOME/ou6M &'
#     # then pull its results in and aggregate the lot:
#     rsync -a server:ou6M/task_* "$RUN"/
#     python3 hpc/aggregate_array.py "$RUN"
#
# Put the output on real disk: a tmpfs /tmp is RAM, and 20 tasks of trajectory
# data in RAM on a small server will not end well.
set -uo pipefail          # deliberately NOT -e: one failed task must not kill the batch

_hpc_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOMEO_SRC="${HOMEO_SRC:-$(cd "$_hpc_dir/.." && pwd)}"
PYTHON="${PYTHON:-python3}"

# Default to PHYSICAL cores, not nproc.  nproc counts hyperthreads, and these
# runs are CPU-bound floating-point work that gains nothing from a second thread
# on the same core -- oversubscribing just makes every run slower.
default_workers() {
    local phys
    phys=$(lscpu -p=Core,Socket 2>/dev/null | grep -v '^#' | sort -u | wc -l)
    [ "${phys:-0}" -ge 1 ] 2>/dev/null && echo "$phys" || echo 1
}

WORKERS=$(default_workers)
FIRST=1
LAST=20
STEPS=6000000
TRAJ_INTERVAL=200
RUNDIR=""
DRY_RUN=0

usage() { sed -n '2,28p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'; exit 0; }

while [ $# -gt 0 ]; do
    case "$1" in
        -n|--workers)  WORKERS="$2"; shift 2;;
        -a|--array)    FIRST="${2%%-*}"; LAST="${2##*-}"; shift 2;;
        -s|--steps)    STEPS="$2"; shift 2;;
        -o|--out)      RUNDIR="$2"; shift 2;;
        --traj-interval) TRAJ_INTERVAL="$2"; shift 2;;
        --dry-run)     DRY_RUN=1; shift;;
        -h|--help)     usage;;
        *) echo "unknown option: $1" >&2; exit 2;;
    esac
done

# Where the results go.  Default beside the Grace layout but clearly marked
# local, under whatever simulations_data_dir() resolves to.
if [ -z "$RUNDIR" ]; then
    data_root=$(cd "$HOMEO_SRC/src" && "$PYTHON" -c \
        'from Helpers.General_Helper_Functions import simulations_data_dir; print(simulations_data_dir())') || {
        echo "!! could not resolve the SimulationsData directory" >&2; exit 1; }
    RUNDIR="$data_root/ou6M-local-$(date +%Y-%m-%d-%H-%M-%S)"
fi
mkdir -p "$RUNDIR/logs"

n_tasks=$(( LAST - FIRST + 1 ))
waves=$(( (n_tasks + WORKERS - 1) / WORKERS ))

echo "== local array run"
echo "   tasks      : $FIRST-$LAST  ($n_tasks tasks)"
echo "   workers    : $WORKERS concurrent  ->  $waves waves"
echo "   steps/task : $STEPS   traj-interval $TRAJ_INTERVAL"
echo "   output     : $RUNDIR"
echo "   code       : $(git -C "$HOMEO_SRC" log --oneline -1 2>/dev/null || echo 'unversioned checkout')"
echo

# Provenance alongside the results, so the directory is self-describing.
{
    echo "generated by hpc/run_array_local.sh on $(date -Is) on $(hostname)"
    echo "tasks $FIRST-$LAST, $WORKERS workers, $STEPS steps, traj-interval $TRAJ_INTERVAL"
    echo "code $(git -C "$HOMEO_SRC" log --oneline -1 2>/dev/null || echo 'unversioned')"
    echo "cpu  $(lscpu 2>/dev/null | sed -n 's/^Model name: *//p' | head -1)"
} > "$RUNDIR/PROVENANCE.txt"

task_done() {   # a task counts as finished once its batch CSV exists
    compgen -G "$RUNDIR/task_$1/*/batch_*.csv" >/dev/null 2>&1
}

run_task() {
    local i="$1" seed=$(( 20260930 + $1 ))
    local tdir="$RUNDIR/task_$i"
    mkdir -p "$tdir" "$RUNDIR/.numba/task_$i"
    # Per-task caches: concurrent tasks must not share a numba cache directory.
    export HOMEO_DATA_DIR="$tdir"
    export NUMBA_CACHE_DIR="$RUNDIR/.numba/task_$i"
    cd "$HOMEO_SRC/src" || return 1
    "$PYTHON" -m HomeoExperiments.KheperaExperiments.phototaxis_braitenberg2_direct \
        --continuous \
        --batch 1 \
        --steps "$STEPS" \
        --seed "$seed" \
        --start-at-rest \
        --traj-interval "$TRAJ_INTERVAL" \
        > "$RUNDIR/logs/task_$i.out" 2>&1
}

started=0; skipped=0
t0=$(date +%s)

for i in $(seq "$FIRST" "$LAST"); do
    if task_done "$i"; then
        echo "   task $i: already complete, skipping"
        skipped=$(( skipped + 1 ))
        continue
    fi
    if [ "$DRY_RUN" -eq 1 ]; then
        echo "   task $i: would run with seed $(( 20260930 + i ))"
        continue
    fi
    # Block until a worker slot frees up.
    while [ "$(jobs -rp | wc -l)" -ge "$WORKERS" ]; do wait -n 2>/dev/null || break; done
    ( run_task "$i" \
        && echo "   task $i done   ($(date +%H:%M:%S))" \
        || echo "   task $i FAILED -- see $RUNDIR/logs/task_$i.out" ) &
    started=$(( started + 1 ))
done

wait
[ "$DRY_RUN" -eq 1 ] && { echo; echo "dry run: nothing executed"; exit 0; }

elapsed=$(( $(date +%s) - t0 ))
echo
printf '== finished: %d started, %d skipped, %dh%02dm elapsed\n' \
       "$started" "$skipped" $(( elapsed / 3600 )) $(( elapsed % 3600 / 60 ))

ok=$(find "$RUNDIR" -name 'batch_*.csv' 2>/dev/null | wc -l)
echo "   tasks with results: $ok/$n_tasks"
if [ "$ok" -lt "$n_tasks" ]; then
    echo "   !! missing results -- check $RUNDIR/logs/"
    echo "      re-run the same command with -o $RUNDIR to retry only the missing tasks"
fi
echo
echo "aggregate with:"
echo "   $PYTHON $_hpc_dir/aggregate_array.py $RUNDIR"
