# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_stagemodule', [dirname(__file__)])
        except ImportError:
            import _stagemodule
            return _stagemodule
        if fp is not None:
            try:
                _mod = imp.load_module('_stagemodule', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _stagemodule = swig_import_helper()
    del swig_import_helper
else:
    import _stagemodule
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def Init(argc, argv):
    return _stagemodule.Init(argc, argv)
Init = _stagemodule.Init

def InitDone():
    return _stagemodule.InitDone()
InitDone = _stagemodule.InitDone

def Version():
    return _stagemodule.Version()
Version = _stagemodule.Version

def rtod(r):
    return _stagemodule.rtod(r)
rtod = _stagemodule.rtod

def dtor(d):
    return _stagemodule.dtor(d)
dtor = _stagemodule.dtor

def normalize(a):
    return _stagemodule.normalize(a)
normalize = _stagemodule.normalize

def sgn(*args):
    return _stagemodule.sgn(*args)
sgn = _stagemodule.sgn

_stagemodule.FiducialNone_swigconstant(_stagemodule)
FiducialNone = _stagemodule.FiducialNone
class Color(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Color, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Color, name)
    __repr__ = _swig_repr
    __swig_setmethods__["r"] = _stagemodule.Color_r_set
    __swig_getmethods__["r"] = _stagemodule.Color_r_get
    if _newclass:
        r = _swig_property(_stagemodule.Color_r_get, _stagemodule.Color_r_set)
    __swig_setmethods__["g"] = _stagemodule.Color_g_set
    __swig_getmethods__["g"] = _stagemodule.Color_g_get
    if _newclass:
        g = _swig_property(_stagemodule.Color_g_get, _stagemodule.Color_g_set)
    __swig_setmethods__["b"] = _stagemodule.Color_b_set
    __swig_getmethods__["b"] = _stagemodule.Color_b_get
    if _newclass:
        b = _swig_property(_stagemodule.Color_b_get, _stagemodule.Color_b_set)
    __swig_setmethods__["a"] = _stagemodule.Color_a_set
    __swig_getmethods__["a"] = _stagemodule.Color_a_get
    if _newclass:
        a = _swig_property(_stagemodule.Color_a_get, _stagemodule.Color_a_set)

    def __init__(self, *args):
        this = _stagemodule.new_Color(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def __ne__(self, other):
        return _stagemodule.Color___ne__(self, other)

    def __eq__(self, other):
        return _stagemodule.Color___eq__(self, other)
    __swig_getmethods__["RandomColor"] = lambda x: _stagemodule.Color_RandomColor
    if _newclass:
        RandomColor = staticmethod(_stagemodule.Color_RandomColor)

    def Print(self, prefix):
        return _stagemodule.Color_Print(self, prefix)

    def Load(self, wf, entity):
        return _stagemodule.Color_Load(self, wf, entity)

    def GLSet(self):
        return _stagemodule.Color_GLSet(self)
    __swig_destroy__ = _stagemodule.delete_Color
    __del__ = lambda self: None
Color_swigregister = _stagemodule.Color_swigregister
Color_swigregister(Color)
cvar = _stagemodule.cvar
COPYRIGHT = cvar.COPYRIGHT
AUTHORS = cvar.AUTHORS
WEBSITE = cvar.WEBSITE
DESCRIPTION = cvar.DESCRIPTION
LICENSE = cvar.LICENSE
thousand = cvar.thousand
million = cvar.million
billion = cvar.billion

def Color_RandomColor():
    return _stagemodule.Color_RandomColor()
Color_RandomColor = _stagemodule.Color_RandomColor
Color.blue = _stagemodule.cvar.Color_blue
Color.red = _stagemodule.cvar.Color_red
Color.green = _stagemodule.cvar.Color_green
Color.yellow = _stagemodule.cvar.Color_yellow
Color.magenta = _stagemodule.cvar.Color_magenta
Color.cyan = _stagemodule.cvar.Color_cyan

class Size(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Size, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Size, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _stagemodule.Size_x_set
    __swig_getmethods__["x"] = _stagemodule.Size_x_get
    if _newclass:
        x = _swig_property(_stagemodule.Size_x_get, _stagemodule.Size_x_set)
    __swig_setmethods__["y"] = _stagemodule.Size_y_set
    __swig_getmethods__["y"] = _stagemodule.Size_y_get
    if _newclass:
        y = _swig_property(_stagemodule.Size_y_get, _stagemodule.Size_y_set)
    __swig_setmethods__["z"] = _stagemodule.Size_z_set
    __swig_getmethods__["z"] = _stagemodule.Size_z_get
    if _newclass:
        z = _swig_property(_stagemodule.Size_z_get, _stagemodule.Size_z_set)

    def __init__(self, *args):
        this = _stagemodule.new_Size(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Load(self, wf, section, keyword):
        return _stagemodule.Size_Load(self, wf, section, keyword)

    def Save(self, wf, section, keyword):
        return _stagemodule.Size_Save(self, wf, section, keyword)

    def Zero(self):
        return _stagemodule.Size_Zero(self)
    __swig_destroy__ = _stagemodule.delete_Size
    __del__ = lambda self: None
Size_swigregister = _stagemodule.Size_swigregister
Size_swigregister(Size)

class Pose(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Pose, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Pose, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _stagemodule.Pose_x_set
    __swig_getmethods__["x"] = _stagemodule.Pose_x_get
    if _newclass:
        x = _swig_property(_stagemodule.Pose_x_get, _stagemodule.Pose_x_set)
    __swig_setmethods__["y"] = _stagemodule.Pose_y_set
    __swig_getmethods__["y"] = _stagemodule.Pose_y_get
    if _newclass:
        y = _swig_property(_stagemodule.Pose_y_get, _stagemodule.Pose_y_set)
    __swig_setmethods__["z"] = _stagemodule.Pose_z_set
    __swig_getmethods__["z"] = _stagemodule.Pose_z_get
    if _newclass:
        z = _swig_property(_stagemodule.Pose_z_get, _stagemodule.Pose_z_set)
    __swig_setmethods__["a"] = _stagemodule.Pose_a_set
    __swig_getmethods__["a"] = _stagemodule.Pose_a_get
    if _newclass:
        a = _swig_property(_stagemodule.Pose_a_get, _stagemodule.Pose_a_set)

    def __init__(self, *args):
        this = _stagemodule.new_Pose(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_Pose
    __del__ = lambda self: None
    __swig_getmethods__["Random"] = lambda x: _stagemodule.Pose_Random
    if _newclass:
        Random = staticmethod(_stagemodule.Pose_Random)

    def Print(self, prefix):
        return _stagemodule.Pose_Print(self, prefix)

    def String(self):
        return _stagemodule.Pose_String(self)

    def IsZero(self):
        return _stagemodule.Pose_IsZero(self)

    def Zero(self):
        return _stagemodule.Pose_Zero(self)

    def Load(self, wf, section, keyword):
        return _stagemodule.Pose_Load(self, wf, section, keyword)

    def Save(self, wf, section, keyword):
        return _stagemodule.Pose_Save(self, wf, section, keyword)

    def __add__(self, p):
        return _stagemodule.Pose___add__(self, p)

    def __lt__(self, p):
        return _stagemodule.Pose___lt__(self, p)

    def __eq__(self, other):
        return _stagemodule.Pose___eq__(self, other)

    def __ne__(self, other):
        return _stagemodule.Pose___ne__(self, other)

    def Distance(self, other):
        return _stagemodule.Pose_Distance(self, other)
Pose_swigregister = _stagemodule.Pose_swigregister
Pose_swigregister(Pose)

def Pose_Random(xmin, xmax, ymin, ymax):
    return _stagemodule.Pose_Random(xmin, xmax, ymin, ymax)
Pose_Random = _stagemodule.Pose_Random

class RaytraceResult(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RaytraceResult, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RaytraceResult, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pose"] = _stagemodule.RaytraceResult_pose_set
    __swig_getmethods__["pose"] = _stagemodule.RaytraceResult_pose_get
    if _newclass:
        pose = _swig_property(_stagemodule.RaytraceResult_pose_get, _stagemodule.RaytraceResult_pose_set)
    __swig_setmethods__["mod"] = _stagemodule.RaytraceResult_mod_set
    __swig_getmethods__["mod"] = _stagemodule.RaytraceResult_mod_get
    if _newclass:
        mod = _swig_property(_stagemodule.RaytraceResult_mod_get, _stagemodule.RaytraceResult_mod_set)
    __swig_setmethods__["color"] = _stagemodule.RaytraceResult_color_set
    __swig_getmethods__["color"] = _stagemodule.RaytraceResult_color_get
    if _newclass:
        color = _swig_property(_stagemodule.RaytraceResult_color_get, _stagemodule.RaytraceResult_color_set)
    __swig_setmethods__["range"] = _stagemodule.RaytraceResult_range_set
    __swig_getmethods__["range"] = _stagemodule.RaytraceResult_range_get
    if _newclass:
        range = _swig_property(_stagemodule.RaytraceResult_range_get, _stagemodule.RaytraceResult_range_set)

    def __init__(self, *args):
        this = _stagemodule.new_RaytraceResult(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_RaytraceResult
    __del__ = lambda self: None
RaytraceResult_swigregister = _stagemodule.RaytraceResult_swigregister
RaytraceResult_swigregister(RaytraceResult)

class Velocity(Pose):
    __swig_setmethods__ = {}
    for _s in [Pose]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Velocity, name, value)
    __swig_getmethods__ = {}
    for _s in [Pose]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Velocity, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _stagemodule.new_Velocity(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Load(self, wf, section, keyword):
        return _stagemodule.Velocity_Load(self, wf, section, keyword)

    def Print(self, prefix):
        return _stagemodule.Velocity_Print(self, prefix)
    __swig_destroy__ = _stagemodule.delete_Velocity
    __del__ = lambda self: None
Velocity_swigregister = _stagemodule.Velocity_swigregister
Velocity_swigregister(Velocity)

class Geom(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Geom, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Geom, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pose"] = _stagemodule.Geom_pose_set
    __swig_getmethods__["pose"] = _stagemodule.Geom_pose_get
    if _newclass:
        pose = _swig_property(_stagemodule.Geom_pose_get, _stagemodule.Geom_pose_set)
    __swig_setmethods__["size"] = _stagemodule.Geom_size_set
    __swig_getmethods__["size"] = _stagemodule.Geom_size_get
    if _newclass:
        size = _swig_property(_stagemodule.Geom_size_get, _stagemodule.Geom_size_set)

    def Print(self, prefix):
        return _stagemodule.Geom_Print(self, prefix)

    def __init__(self, *args):
        this = _stagemodule.new_Geom(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Zero(self):
        return _stagemodule.Geom_Zero(self)
    __swig_destroy__ = _stagemodule.delete_Geom
    __del__ = lambda self: None
Geom_swigregister = _stagemodule.Geom_swigregister
Geom_swigregister(Geom)

class Bounds(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Bounds, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Bounds, name)
    __repr__ = _swig_repr
    __swig_setmethods__["min"] = _stagemodule.Bounds_min_set
    __swig_getmethods__["min"] = _stagemodule.Bounds_min_get
    if _newclass:
        min = _swig_property(_stagemodule.Bounds_min_get, _stagemodule.Bounds_min_set)
    __swig_setmethods__["max"] = _stagemodule.Bounds_max_set
    __swig_getmethods__["max"] = _stagemodule.Bounds_max_get
    if _newclass:
        max = _swig_property(_stagemodule.Bounds_max_get, _stagemodule.Bounds_max_set)

    def __init__(self, *args):
        this = _stagemodule.new_Bounds(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Load(self, wf, section, keyword):
        return _stagemodule.Bounds_Load(self, wf, section, keyword)

    def Constrain(self, value):
        return _stagemodule.Bounds_Constrain(self, value)
    __swig_destroy__ = _stagemodule.delete_Bounds
    __del__ = lambda self: None
Bounds_swigregister = _stagemodule.Bounds_swigregister
Bounds_swigregister(Bounds)

class bounds3d_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, bounds3d_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, bounds3d_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _stagemodule.bounds3d_t_x_set
    __swig_getmethods__["x"] = _stagemodule.bounds3d_t_x_get
    if _newclass:
        x = _swig_property(_stagemodule.bounds3d_t_x_get, _stagemodule.bounds3d_t_x_set)
    __swig_setmethods__["y"] = _stagemodule.bounds3d_t_y_set
    __swig_getmethods__["y"] = _stagemodule.bounds3d_t_y_get
    if _newclass:
        y = _swig_property(_stagemodule.bounds3d_t_y_get, _stagemodule.bounds3d_t_y_set)
    __swig_setmethods__["z"] = _stagemodule.bounds3d_t_z_set
    __swig_getmethods__["z"] = _stagemodule.bounds3d_t_z_get
    if _newclass:
        z = _swig_property(_stagemodule.bounds3d_t_z_get, _stagemodule.bounds3d_t_z_set)

    def __init__(self, *args):
        this = _stagemodule.new_bounds3d_t(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_bounds3d_t
    __del__ = lambda self: None
bounds3d_t_swigregister = _stagemodule.bounds3d_t_swigregister
bounds3d_t_swigregister(bounds3d_t)

class fov_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, fov_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, fov_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["range"] = _stagemodule.fov_t_range_set
    __swig_getmethods__["range"] = _stagemodule.fov_t_range_get
    if _newclass:
        range = _swig_property(_stagemodule.fov_t_range_get, _stagemodule.fov_t_range_set)
    __swig_setmethods__["angle"] = _stagemodule.fov_t_angle_set
    __swig_getmethods__["angle"] = _stagemodule.fov_t_angle_get
    if _newclass:
        angle = _swig_property(_stagemodule.fov_t_angle_get, _stagemodule.fov_t_angle_set)

    def __init__(self):
        this = _stagemodule.new_fov_t()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_fov_t
    __del__ = lambda self: None
fov_t_swigregister = _stagemodule.fov_t_swigregister
fov_t_swigregister(fov_t)

class point_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, point_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, point_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _stagemodule.point_t_x_set
    __swig_getmethods__["x"] = _stagemodule.point_t_x_get
    if _newclass:
        x = _swig_property(_stagemodule.point_t_x_get, _stagemodule.point_t_x_set)
    __swig_setmethods__["y"] = _stagemodule.point_t_y_set
    __swig_getmethods__["y"] = _stagemodule.point_t_y_get
    if _newclass:
        y = _swig_property(_stagemodule.point_t_y_get, _stagemodule.point_t_y_set)

    def __init__(self, *args):
        this = _stagemodule.new_point_t(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def __iadd__(self, other):
        return _stagemodule.point_t___iadd__(self, other)

    def __lt__(self, other):
        return _stagemodule.point_t___lt__(self, other)

    def __eq__(self, other):
        return _stagemodule.point_t___eq__(self, other)
    __swig_destroy__ = _stagemodule.delete_point_t
    __del__ = lambda self: None
point_t_swigregister = _stagemodule.point_t_swigregister
point_t_swigregister(point_t)

class point3_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, point3_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, point3_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _stagemodule.point3_t_x_set
    __swig_getmethods__["x"] = _stagemodule.point3_t_x_get
    if _newclass:
        x = _swig_property(_stagemodule.point3_t_x_get, _stagemodule.point3_t_x_set)
    __swig_setmethods__["y"] = _stagemodule.point3_t_y_set
    __swig_getmethods__["y"] = _stagemodule.point3_t_y_get
    if _newclass:
        y = _swig_property(_stagemodule.point3_t_y_get, _stagemodule.point3_t_y_set)
    __swig_setmethods__["z"] = _stagemodule.point3_t_z_set
    __swig_getmethods__["z"] = _stagemodule.point3_t_z_get
    if _newclass:
        z = _swig_property(_stagemodule.point3_t_z_get, _stagemodule.point3_t_z_set)

    def __init__(self, *args):
        this = _stagemodule.new_point3_t(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_point3_t
    __del__ = lambda self: None
point3_t_swigregister = _stagemodule.point3_t_swigregister
point3_t_swigregister(point3_t)

class point_int_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, point_int_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, point_int_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _stagemodule.point_int_t_x_set
    __swig_getmethods__["x"] = _stagemodule.point_int_t_x_get
    if _newclass:
        x = _swig_property(_stagemodule.point_int_t_x_get, _stagemodule.point_int_t_x_set)
    __swig_setmethods__["y"] = _stagemodule.point_int_t_y_set
    __swig_getmethods__["y"] = _stagemodule.point_int_t_y_get
    if _newclass:
        y = _swig_property(_stagemodule.point_int_t_y_get, _stagemodule.point_int_t_y_set)

    def __init__(self, *args):
        this = _stagemodule.new_point_int_t(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def __lt__(self, other):
        return _stagemodule.point_int_t___lt__(self, other)

    def __eq__(self, other):
        return _stagemodule.point_int_t___eq__(self, other)
    __swig_destroy__ = _stagemodule.delete_point_int_t
    __del__ = lambda self: None
point_int_t_swigregister = _stagemodule.point_int_t_swigregister
point_int_t_swigregister(point_int_t)


def unit_square_points_create():
    return _stagemodule.unit_square_points_create()
unit_square_points_create = _stagemodule.unit_square_points_create

def pose_shift(pose):
    return _stagemodule.pose_shift(pose)
pose_shift = _stagemodule.pose_shift

def pose_inverse_shift(pose):
    return _stagemodule.pose_inverse_shift(pose)
pose_inverse_shift = _stagemodule.pose_inverse_shift

def coord_shift(x, y, z, a):
    return _stagemodule.coord_shift(x, y, z, a)
coord_shift = _stagemodule.coord_shift

def draw_grid(vol):
    return _stagemodule.draw_grid(vol)
draw_grid = _stagemodule.draw_grid

def draw_string(x, y, z, string):
    return _stagemodule.draw_string(x, y, z, string)
draw_string = _stagemodule.draw_string

def draw_string_multiline(x, y, w, h, string, align):
    return _stagemodule.draw_string_multiline(x, y, w, h, string, align)
draw_string_multiline = _stagemodule.draw_string_multiline

def draw_speech_bubble(x, y, z, str):
    return _stagemodule.draw_speech_bubble(x, y, z, str)
draw_speech_bubble = _stagemodule.draw_speech_bubble

def draw_octagon(*args):
    return _stagemodule.draw_octagon(*args)
draw_octagon = _stagemodule.draw_octagon

def draw_vector(x, y, z):
    return _stagemodule.draw_vector(x, y, z)
draw_vector = _stagemodule.draw_vector

def draw_origin(len):
    return _stagemodule.draw_origin(len)
draw_origin = _stagemodule.draw_origin

def draw_array(*args):
    return _stagemodule.draw_array(*args)
draw_array = _stagemodule.draw_array

def draw_centered_rect(x, y, dx, dy):
    return _stagemodule.draw_centered_rect(x, y, dx, dy)
draw_centered_rect = _stagemodule.draw_centered_rect

def RegisterModels():
    return _stagemodule.RegisterModels()
RegisterModels = _stagemodule.RegisterModels
class Visualizer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Visualizer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Visualizer, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _stagemodule.delete_Visualizer
    __del__ = lambda self: None

    def Visualize(self, mod, cam):
        return _stagemodule.Visualizer_Visualize(self, mod, cam)

    def GetMenuName(self):
        return _stagemodule.Visualizer_GetMenuName(self)

    def GetWorldfileName(self):
        return _stagemodule.Visualizer_GetWorldfileName(self)
Visualizer_swigregister = _stagemodule.Visualizer_swigregister
Visualizer_swigregister(Visualizer)


def constrain(val, minval, maxval):
    return _stagemodule.constrain(val, minval, maxval)
constrain = _stagemodule.constrain
class blinkenlight_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, blinkenlight_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, blinkenlight_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["enabled"] = _stagemodule.blinkenlight_t_enabled_set
    __swig_getmethods__["enabled"] = _stagemodule.blinkenlight_t_enabled_get
    if _newclass:
        enabled = _swig_property(_stagemodule.blinkenlight_t_enabled_get, _stagemodule.blinkenlight_t_enabled_set)
    __swig_setmethods__["pose"] = _stagemodule.blinkenlight_t_pose_set
    __swig_getmethods__["pose"] = _stagemodule.blinkenlight_t_pose_get
    if _newclass:
        pose = _swig_property(_stagemodule.blinkenlight_t_pose_get, _stagemodule.blinkenlight_t_pose_set)
    __swig_setmethods__["size"] = _stagemodule.blinkenlight_t_size_set
    __swig_getmethods__["size"] = _stagemodule.blinkenlight_t_size_get
    if _newclass:
        size = _swig_property(_stagemodule.blinkenlight_t_size_get, _stagemodule.blinkenlight_t_size_set)
    __swig_setmethods__["color"] = _stagemodule.blinkenlight_t_color_set
    __swig_getmethods__["color"] = _stagemodule.blinkenlight_t_color_get
    if _newclass:
        color = _swig_property(_stagemodule.blinkenlight_t_color_get, _stagemodule.blinkenlight_t_color_set)
    __swig_setmethods__["period"] = _stagemodule.blinkenlight_t_period_set
    __swig_getmethods__["period"] = _stagemodule.blinkenlight_t_period_get
    if _newclass:
        period = _swig_property(_stagemodule.blinkenlight_t_period_get, _stagemodule.blinkenlight_t_period_set)
    __swig_setmethods__["duty_cycle"] = _stagemodule.blinkenlight_t_duty_cycle_set
    __swig_getmethods__["duty_cycle"] = _stagemodule.blinkenlight_t_duty_cycle_get
    if _newclass:
        duty_cycle = _swig_property(_stagemodule.blinkenlight_t_duty_cycle_get, _stagemodule.blinkenlight_t_duty_cycle_set)

    def __init__(self):
        this = _stagemodule.new_blinkenlight_t()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_blinkenlight_t
    __del__ = lambda self: None
blinkenlight_t_swigregister = _stagemodule.blinkenlight_t_swigregister
blinkenlight_t_swigregister(blinkenlight_t)

class rotrect_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rotrect_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rotrect_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pose"] = _stagemodule.rotrect_t_pose_set
    __swig_getmethods__["pose"] = _stagemodule.rotrect_t_pose_get
    if _newclass:
        pose = _swig_property(_stagemodule.rotrect_t_pose_get, _stagemodule.rotrect_t_pose_set)
    __swig_setmethods__["size"] = _stagemodule.rotrect_t_size_set
    __swig_getmethods__["size"] = _stagemodule.rotrect_t_size_get
    if _newclass:
        size = _swig_property(_stagemodule.rotrect_t_size_get, _stagemodule.rotrect_t_size_set)

    def __init__(self):
        this = _stagemodule.new_rotrect_t()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_rotrect_t
    __del__ = lambda self: None
rotrect_t_swigregister = _stagemodule.rotrect_t_swigregister
rotrect_t_swigregister(rotrect_t)


def polys_from_image_file(filename, polys):
    return _stagemodule.polys_from_image_file(filename, polys)
polys_from_image_file = _stagemodule.polys_from_image_file
class Ancestor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Ancestor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Ancestor, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _stagemodule.new_Ancestor()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_Ancestor
    __del__ = lambda self: None

    def GetChildren(self):
        return _stagemodule.Ancestor_GetChildren(self)

    def ForEachDescendant(self, func, arg):
        return _stagemodule.Ancestor_ForEachDescendant(self, func, arg)

    def AddChild(self, mod):
        return _stagemodule.Ancestor_AddChild(self, mod)

    def RemoveChild(self, mod):
        return _stagemodule.Ancestor_RemoveChild(self, mod)

    def GetGlobalPose(self):
        return _stagemodule.Ancestor_GetGlobalPose(self)

    def Token(self):
        return _stagemodule.Ancestor_Token(self)

    def TokenStr(self):
        return _stagemodule.Ancestor_TokenStr(self)

    def SetToken(self, str):
        return _stagemodule.Ancestor_SetToken(self, str)

    def SetProperty(self, key, value):
        return _stagemodule.Ancestor_SetProperty(self, key, value)

    def GetProperty(self, key):
        return _stagemodule.Ancestor_GetProperty(self, key)
Ancestor_swigregister = _stagemodule.Ancestor_swigregister
Ancestor_swigregister(Ancestor)

class Ray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Ray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Ray, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _stagemodule.new_Ray(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_setmethods__["mod"] = _stagemodule.Ray_mod_set
    __swig_getmethods__["mod"] = _stagemodule.Ray_mod_get
    if _newclass:
        mod = _swig_property(_stagemodule.Ray_mod_get, _stagemodule.Ray_mod_set)
    __swig_setmethods__["origin"] = _stagemodule.Ray_origin_set
    __swig_getmethods__["origin"] = _stagemodule.Ray_origin_get
    if _newclass:
        origin = _swig_property(_stagemodule.Ray_origin_get, _stagemodule.Ray_origin_set)
    __swig_setmethods__["range"] = _stagemodule.Ray_range_set
    __swig_getmethods__["range"] = _stagemodule.Ray_range_get
    if _newclass:
        range = _swig_property(_stagemodule.Ray_range_get, _stagemodule.Ray_range_set)
    __swig_setmethods__["func"] = _stagemodule.Ray_func_set
    __swig_getmethods__["func"] = _stagemodule.Ray_func_get
    if _newclass:
        func = _swig_property(_stagemodule.Ray_func_get, _stagemodule.Ray_func_set)
    __swig_setmethods__["arg"] = _stagemodule.Ray_arg_set
    __swig_getmethods__["arg"] = _stagemodule.Ray_arg_get
    if _newclass:
        arg = _swig_property(_stagemodule.Ray_arg_get, _stagemodule.Ray_arg_set)
    __swig_setmethods__["ztest"] = _stagemodule.Ray_ztest_set
    __swig_getmethods__["ztest"] = _stagemodule.Ray_ztest_get
    if _newclass:
        ztest = _swig_property(_stagemodule.Ray_ztest_get, _stagemodule.Ray_ztest_set)
    __swig_destroy__ = _stagemodule.delete_Ray
    __del__ = lambda self: None
Ray_swigregister = _stagemodule.Ray_swigregister
Ray_swigregister(Ray)

class LogEntry(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LogEntry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LogEntry, name)
    __repr__ = _swig_repr

    def __init__(self, timestamp, mod):
        this = _stagemodule.new_LogEntry(timestamp, mod)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_setmethods__["log"] = _stagemodule.LogEntry_log_set
    __swig_getmethods__["log"] = _stagemodule.LogEntry_log_get
    if _newclass:
        log = _swig_property(_stagemodule.LogEntry_log_get, _stagemodule.LogEntry_log_set)
    __swig_getmethods__["Count"] = lambda x: _stagemodule.LogEntry_Count
    if _newclass:
        Count = staticmethod(_stagemodule.LogEntry_Count)
    __swig_getmethods__["Clear"] = lambda x: _stagemodule.LogEntry_Clear
    if _newclass:
        Clear = staticmethod(_stagemodule.LogEntry_Clear)
    __swig_getmethods__["Print"] = lambda x: _stagemodule.LogEntry_Print
    if _newclass:
        Print = staticmethod(_stagemodule.LogEntry_Print)
    __swig_destroy__ = _stagemodule.delete_LogEntry
    __del__ = lambda self: None
LogEntry_swigregister = _stagemodule.LogEntry_swigregister
LogEntry_swigregister(LogEntry)

def LogEntry_Count():
    return _stagemodule.LogEntry_Count()
LogEntry_Count = _stagemodule.LogEntry_Count

def LogEntry_Clear():
    return _stagemodule.LogEntry_Clear()
LogEntry_Clear = _stagemodule.LogEntry_Clear

def LogEntry_Print():
    return _stagemodule.LogEntry_Print()
LogEntry_Print = _stagemodule.LogEntry_Print

class CtrlArgs(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CtrlArgs, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CtrlArgs, name)
    __repr__ = _swig_repr
    __swig_setmethods__["worldfile"] = _stagemodule.CtrlArgs_worldfile_set
    __swig_getmethods__["worldfile"] = _stagemodule.CtrlArgs_worldfile_get
    if _newclass:
        worldfile = _swig_property(_stagemodule.CtrlArgs_worldfile_get, _stagemodule.CtrlArgs_worldfile_set)
    __swig_setmethods__["cmdline"] = _stagemodule.CtrlArgs_cmdline_set
    __swig_getmethods__["cmdline"] = _stagemodule.CtrlArgs_cmdline_get
    if _newclass:
        cmdline = _swig_property(_stagemodule.CtrlArgs_cmdline_get, _stagemodule.CtrlArgs_cmdline_set)

    def __init__(self, w, c):
        this = _stagemodule.new_CtrlArgs(w, c)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_CtrlArgs
    __del__ = lambda self: None
CtrlArgs_swigregister = _stagemodule.CtrlArgs_swigregister
CtrlArgs_swigregister(CtrlArgs)

class World(Ancestor):
    __swig_setmethods__ = {}
    for _s in [Ancestor]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, World, name, value)
    __swig_getmethods__ = {}
    for _s in [Ancestor]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, World, name)
    __repr__ = _swig_repr
    __swig_setmethods__["args"] = _stagemodule.World_args_set
    __swig_getmethods__["args"] = _stagemodule.World_args_get
    if _newclass:
        args = _swig_property(_stagemodule.World_args_get, _stagemodule.World_args_set)
    __swig_setmethods__["ctrlargs"] = _stagemodule.World_ctrlargs_set
    __swig_getmethods__["ctrlargs"] = _stagemodule.World_ctrlargs_get
    if _newclass:
        ctrlargs = _swig_property(_stagemodule.World_ctrlargs_get, _stagemodule.World_ctrlargs_set)

    def UpdateCount(self):
        return _stagemodule.World_UpdateCount(self)
    __swig_setmethods__["paused"] = _stagemodule.World_paused_set
    __swig_getmethods__["paused"] = _stagemodule.World_paused_get
    if _newclass:
        paused = _swig_property(_stagemodule.World_paused_get, _stagemodule.World_paused_set)

    def Start(self):
        return _stagemodule.World_Start(self)

    def Stop(self):
        return _stagemodule.World_Stop(self)

    def TogglePause(self):
        return _stagemodule.World_TogglePause(self)

    def Paused(self):
        return _stagemodule.World_Paused(self)

    def Redraw(self):
        return _stagemodule.World_Redraw(self)
    __swig_setmethods__["rt_cells"] = _stagemodule.World_rt_cells_set
    __swig_getmethods__["rt_cells"] = _stagemodule.World_rt_cells_get
    if _newclass:
        rt_cells = _swig_property(_stagemodule.World_rt_cells_get, _stagemodule.World_rt_cells_set)
    __swig_setmethods__["rt_candidate_cells"] = _stagemodule.World_rt_candidate_cells_set
    __swig_getmethods__["rt_candidate_cells"] = _stagemodule.World_rt_candidate_cells_get
    if _newclass:
        rt_candidate_cells = _swig_property(_stagemodule.World_rt_candidate_cells_get, _stagemodule.World_rt_candidate_cells_set)
    DEFAULT_PPM = _stagemodule.World_DEFAULT_PPM

    def AddUpdateCallback(self, cb, user):
        return _stagemodule.World_AddUpdateCallback(self, cb, user)

    def RemoveUpdateCallback(self, cb, user):
        return _stagemodule.World_RemoveUpdateCallback(self, cb, user)

    def Log(self, mod):
        return _stagemodule.World_Log(self, mod)

    def NeedRedraw(self):
        return _stagemodule.World_NeedRedraw(self)
    __swig_setmethods__["ground"] = _stagemodule.World_ground_set
    __swig_getmethods__["ground"] = _stagemodule.World_ground_get
    if _newclass:
        ground = _swig_property(_stagemodule.World_ground_get, _stagemodule.World_ground_set)

    def ClockString(self):
        return _stagemodule.World_ClockString(self)

    def CreateModel(self, parent, typestr):
        return _stagemodule.World_CreateModel(self, parent, typestr)

    def LoadModel(self, wf, entity):
        return _stagemodule.World_LoadModel(self, wf, entity)

    def LoadBlock(self, wf, entity):
        return _stagemodule.World_LoadBlock(self, wf, entity)

    def LoadBlockGroup(self, wf, entity):
        return _stagemodule.World_LoadBlockGroup(self, wf, entity)

    def LoadSensor(self, wf, entity):
        return _stagemodule.World_LoadSensor(self, wf, entity)

    def RecentlySelectedModel(self):
        return _stagemodule.World_RecentlySelectedModel(self)

    def MapPoly(self, poly, block, layer):
        return _stagemodule.World_MapPoly(self, poly, block, layer)

    def AddSuperRegion(self, coord):
        return _stagemodule.World_AddSuperRegion(self, coord)

    def GetSuperRegion(self, org):
        return _stagemodule.World_GetSuperRegion(self, org)

    def GetSuperRegionCreate(self, org):
        return _stagemodule.World_GetSuperRegionCreate(self, org)

    def MetersToPixels(self, *args):
        return _stagemodule.World_MetersToPixels(self, *args)

    def PushColor(self, *args):
        return _stagemodule.World_PushColor(self, *args)

    def PopColor(self):
        return _stagemodule.World_PopColor(self)

    def CreateSuperRegion(self, origin):
        return _stagemodule.World_CreateSuperRegion(self, origin)

    def DestroySuperRegion(self, sr):
        return _stagemodule.World_DestroySuperRegion(self, sr)

    def Raytrace(self, *args):
        return _stagemodule.World_Raytrace(self, *args)

    def Extend(self, pt):
        return _stagemodule.World_Extend(self, pt)

    def AddModel(self, mod):
        return _stagemodule.World_AddModel(self, mod)

    def RemoveModel(self, mod):
        return _stagemodule.World_RemoveModel(self, mod)

    def AddModelName(self, mod, name):
        return _stagemodule.World_AddModelName(self, mod, name)

    def AddPowerPack(self, pp):
        return _stagemodule.World_AddPowerPack(self, pp)

    def RemovePowerPack(self, pp):
        return _stagemodule.World_RemovePowerPack(self, pp)

    def ClearRays(self):
        return _stagemodule.World_ClearRays(self)

    def RecordRay(self, x1, y1, x2, y2):
        return _stagemodule.World_RecordRay(self, x1, y1, x2, y2)

    def PastQuitTime(self):
        return _stagemodule.World_PastQuitTime(self)
    __swig_getmethods__["update_thread_entry"] = lambda x: _stagemodule.World_update_thread_entry
    if _newclass:
        update_thread_entry = staticmethod(_stagemodule.World_update_thread_entry)
    __swig_setmethods__["event_queues"] = _stagemodule.World_event_queues_set
    __swig_getmethods__["event_queues"] = _stagemodule.World_event_queues_get
    if _newclass:
        event_queues = _swig_property(_stagemodule.World_event_queues_get, _stagemodule.World_event_queues_set)
    __swig_setmethods__["pending_update_callbacks"] = _stagemodule.World_pending_update_callbacks_set
    __swig_getmethods__["pending_update_callbacks"] = _stagemodule.World_pending_update_callbacks_get
    if _newclass:
        pending_update_callbacks = _swig_property(_stagemodule.World_pending_update_callbacks_get, _stagemodule.World_pending_update_callbacks_set)

    def Enqueue(self, queue_num, delay, mod, cb, arg):
        return _stagemodule.World_Enqueue(self, queue_num, delay, mod, cb, arg)
    __swig_setmethods__["active_energy"] = _stagemodule.World_active_energy_set
    __swig_getmethods__["active_energy"] = _stagemodule.World_active_energy_get
    if _newclass:
        active_energy = _swig_property(_stagemodule.World_active_energy_get, _stagemodule.World_active_energy_set)

    def EnableEnergy(self, m):
        return _stagemodule.World_EnableEnergy(self, m)

    def DisableEnergy(self, m):
        return _stagemodule.World_DisableEnergy(self, m)
    __swig_setmethods__["active_velocity"] = _stagemodule.World_active_velocity_set
    __swig_getmethods__["active_velocity"] = _stagemodule.World_active_velocity_get
    if _newclass:
        active_velocity = _swig_property(_stagemodule.World_active_velocity_get, _stagemodule.World_active_velocity_set)
    __swig_setmethods__["sim_interval"] = _stagemodule.World_sim_interval_set
    __swig_getmethods__["sim_interval"] = _stagemodule.World_sim_interval_get
    if _newclass:
        sim_interval = _swig_property(_stagemodule.World_sim_interval_get, _stagemodule.World_sim_interval_set)
    __swig_setmethods__["update_cb_count"] = _stagemodule.World_update_cb_count_set
    __swig_getmethods__["update_cb_count"] = _stagemodule.World_update_cb_count_get
    if _newclass:
        update_cb_count = _swig_property(_stagemodule.World_update_cb_count_get, _stagemodule.World_update_cb_count_set)

    def ConsumeQueue(self, queue_num):
        return _stagemodule.World_ConsumeQueue(self, queue_num)

    def GetEventQueue(self, mod):
        return _stagemodule.World_GetEventQueue(self, mod)
    __swig_getmethods__["UpdateAll"] = lambda x: _stagemodule.World_UpdateAll
    if _newclass:
        UpdateAll = staticmethod(_stagemodule.World_UpdateAll)
    __swig_getmethods__["Run"] = lambda x: _stagemodule.World_Run
    if _newclass:
        Run = staticmethod(_stagemodule.World_Run)

    def __init__(self, *args):
        this = _stagemodule.new_World(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_World
    __del__ = lambda self: None

    def SimTimeNow(self):
        return _stagemodule.World_SimTimeNow(self)

    def GetWorldFile(self):
        return _stagemodule.World_GetWorldFile(self)

    def IsGUI(self):
        return _stagemodule.World_IsGUI(self)

    def Load(self, worldfile_path):
        return _stagemodule.World_Load(self, worldfile_path)

    def UnLoad(self):
        return _stagemodule.World_UnLoad(self)

    def Reload(self):
        return _stagemodule.World_Reload(self)

    def Save(self, filename):
        return _stagemodule.World_Save(self, filename)

    def Update(self):
        return _stagemodule.World_Update(self)

    def TestQuit(self):
        return _stagemodule.World_TestQuit(self)

    def Quit(self):
        return _stagemodule.World_Quit(self)

    def QuitAll(self):
        return _stagemodule.World_QuitAll(self)

    def CancelQuit(self):
        return _stagemodule.World_CancelQuit(self)

    def CancelQuitAll(self):
        return _stagemodule.World_CancelQuitAll(self)

    def TryCharge(self, pp, pose):
        return _stagemodule.World_TryCharge(self, pp, pose)

    def Resolution(self):
        return _stagemodule.World_Resolution(self)

    def GetModel(self, name):
        return _stagemodule.World_GetModel(self, name)

    def GetAllModels(self):
        return _stagemodule.World_GetAllModels(self)

    def GetExtent(self):
        return _stagemodule.World_GetExtent(self)

    def GetUpdateCount(self):
        return _stagemodule.World_GetUpdateCount(self)

    def RegisterOption(self, opt):
        return _stagemodule.World_RegisterOption(self, opt)

    def ShowClock(self, enable):
        return _stagemodule.World_ShowClock(self, enable)

    def GetGround(self):
        return _stagemodule.World_GetGround(self)
World_swigregister = _stagemodule.World_swigregister
World_swigregister(World)

def World_update_thread_entry(info):
    return _stagemodule.World_update_thread_entry(info)
World_update_thread_entry = _stagemodule.World_update_thread_entry

def World_UpdateAll():
    return _stagemodule.World_UpdateAll()
World_UpdateAll = _stagemodule.World_UpdateAll

def World_Run():
    return _stagemodule.World_Run()
World_Run = _stagemodule.World_Run

class Block(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Block, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Block, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _stagemodule.new_Block(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_Block
    __del__ = lambda self: None

    def Map(self, layer):
        return _stagemodule.Block_Map(self, layer)

    def UnMap(self, layer):
        return _stagemodule.Block_UnMap(self, layer)

    def DrawSolid(self, topview):
        return _stagemodule.Block_DrawSolid(self, topview)

    def DrawFootPrint(self):
        return _stagemodule.Block_DrawFootPrint(self)

    def Translate(self, x, y):
        return _stagemodule.Block_Translate(self, x, y)

    def CenterX(self):
        return _stagemodule.Block_CenterX(self)

    def CenterY(self):
        return _stagemodule.Block_CenterY(self)

    def SetCenterX(self, y):
        return _stagemodule.Block_SetCenterX(self, y)

    def SetCenterY(self, y):
        return _stagemodule.Block_SetCenterY(self, y)

    def SetCenter(self, x, y):
        return _stagemodule.Block_SetCenter(self, x, y)

    def SetZ(self, min, max):
        return _stagemodule.Block_SetZ(self, min, max)

    def AppendTouchingModels(self, touchers):
        return _stagemodule.Block_AppendTouchingModels(self, touchers)

    def TestCollision(self):
        return _stagemodule.Block_TestCollision(self)

    def Load(self, wf, entity):
        return _stagemodule.Block_Load(self, wf, entity)

    def Rasterize(self, data, width, height, cellwidth, cellheight):
        return _stagemodule.Block_Rasterize(self, data, width, height, cellwidth, cellheight)
    __swig_setmethods__["group"] = _stagemodule.Block_group_set
    __swig_getmethods__["group"] = _stagemodule.Block_group_get
    if _newclass:
        group = _swig_property(_stagemodule.Block_group_get, _stagemodule.Block_group_set)
Block_swigregister = _stagemodule.Block_swigregister
Block_swigregister(Block)

class BlockGroup(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlockGroup, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BlockGroup, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mod"] = _stagemodule.BlockGroup_mod_set
    __swig_getmethods__["mod"] = _stagemodule.BlockGroup_mod_get
    if _newclass:
        mod = _swig_property(_stagemodule.BlockGroup_mod_get, _stagemodule.BlockGroup_mod_set)

    def __init__(self, mod):
        this = _stagemodule.new_BlockGroup(mod)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_BlockGroup
    __del__ = lambda self: None

    def GetCount(self):
        return _stagemodule.BlockGroup_GetCount(self)

    def GetBlock(self, index):
        return _stagemodule.BlockGroup_GetBlock(self, index)

    def GetBlockMutable(self, index):
        return _stagemodule.BlockGroup_GetBlockMutable(self, index)

    def BoundingBox(self):
        return _stagemodule.BlockGroup_BoundingBox(self)

    def DrawFootPrint(self, geom):
        return _stagemodule.BlockGroup_DrawFootPrint(self, geom)
BlockGroup_swigregister = _stagemodule.BlockGroup_swigregister
BlockGroup_swigregister(BlockGroup)

class Camera(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Camera, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Camera, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _stagemodule.delete_Camera
    __del__ = lambda self: None

    def Draw(self):
        return _stagemodule.Camera_Draw(self)

    def SetProjection(self):
        return _stagemodule.Camera_SetProjection(self)

    def yaw(self):
        return _stagemodule.Camera_yaw(self)

    def pitch(self):
        return _stagemodule.Camera_pitch(self)

    def x(self):
        return _stagemodule.Camera_x(self)

    def y(self):
        return _stagemodule.Camera_y(self)

    def z(self):
        return _stagemodule.Camera_z(self)

    def reset(self):
        return _stagemodule.Camera_reset(self)

    def Load(self, wf, sec):
        return _stagemodule.Camera_Load(self, wf, sec)
Camera_swigregister = _stagemodule.Camera_swigregister
Camera_swigregister(Camera)

class PerspectiveCamera(Camera):
    __swig_setmethods__ = {}
    for _s in [Camera]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PerspectiveCamera, name, value)
    __swig_getmethods__ = {}
    for _s in [Camera]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PerspectiveCamera, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _stagemodule.new_PerspectiveCamera()
        try:
            self.this.append(this)
        except:
            self.this = this

    def Draw(self):
        return _stagemodule.PerspectiveCamera_Draw(self)

    def SetProjection(self):
        return _stagemodule.PerspectiveCamera_SetProjection(self)

    def update(self):
        return _stagemodule.PerspectiveCamera_update(self)

    def strafe(self, amount):
        return _stagemodule.PerspectiveCamera_strafe(self, amount)

    def forward(self, amount):
        return _stagemodule.PerspectiveCamera_forward(self, amount)

    def setPose(self, x, y, z):
        return _stagemodule.PerspectiveCamera_setPose(self, x, y, z)

    def addPose(self, x, y, z):
        return _stagemodule.PerspectiveCamera_addPose(self, x, y, z)

    def move(self, x, y, z):
        return _stagemodule.PerspectiveCamera_move(self, x, y, z)

    def setFov(self, horiz_fov, vert_fov):
        return _stagemodule.PerspectiveCamera_setFov(self, horiz_fov, vert_fov)

    def setAspect(self, aspect):
        return _stagemodule.PerspectiveCamera_setAspect(self, aspect)

    def setYaw(self, yaw):
        return _stagemodule.PerspectiveCamera_setYaw(self, yaw)

    def horizFov(self):
        return _stagemodule.PerspectiveCamera_horizFov(self)

    def vertFov(self):
        return _stagemodule.PerspectiveCamera_vertFov(self)

    def addYaw(self, yaw):
        return _stagemodule.PerspectiveCamera_addYaw(self, yaw)

    def setPitch(self, pitch):
        return _stagemodule.PerspectiveCamera_setPitch(self, pitch)

    def addPitch(self, pitch):
        return _stagemodule.PerspectiveCamera_addPitch(self, pitch)

    def realDistance(self, z_buf_val):
        return _stagemodule.PerspectiveCamera_realDistance(self, z_buf_val)

    def scroll(self, dy):
        return _stagemodule.PerspectiveCamera_scroll(self, dy)

    def nearClip(self):
        return _stagemodule.PerspectiveCamera_nearClip(self)

    def farClip(self):
        return _stagemodule.PerspectiveCamera_farClip(self)

    def setClip(self, near, far):
        return _stagemodule.PerspectiveCamera_setClip(self, near, far)

    def reset(self):
        return _stagemodule.PerspectiveCamera_reset(self)

    def Load(self, wf, sec):
        return _stagemodule.PerspectiveCamera_Load(self, wf, sec)

    def Save(self, wf, sec):
        return _stagemodule.PerspectiveCamera_Save(self, wf, sec)
    __swig_destroy__ = _stagemodule.delete_PerspectiveCamera
    __del__ = lambda self: None
PerspectiveCamera_swigregister = _stagemodule.PerspectiveCamera_swigregister
PerspectiveCamera_swigregister(PerspectiveCamera)

class OrthoCamera(Camera):
    __swig_setmethods__ = {}
    for _s in [Camera]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, OrthoCamera, name, value)
    __swig_getmethods__ = {}
    for _s in [Camera]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, OrthoCamera, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _stagemodule.new_OrthoCamera()
        try:
            self.this.append(this)
        except:
            self.this = this

    def Draw(self):
        return _stagemodule.OrthoCamera_Draw(self)

    def SetProjection(self, *args):
        return _stagemodule.OrthoCamera_SetProjection(self, *args)

    def move(self, x, y):
        return _stagemodule.OrthoCamera_move(self, x, y)

    def setYaw(self, yaw):
        return _stagemodule.OrthoCamera_setYaw(self, yaw)

    def setPitch(self, pitch):
        return _stagemodule.OrthoCamera_setPitch(self, pitch)

    def addYaw(self, yaw):
        return _stagemodule.OrthoCamera_addYaw(self, yaw)

    def addPitch(self, pitch):
        return _stagemodule.OrthoCamera_addPitch(self, pitch)

    def setScale(self, scale):
        return _stagemodule.OrthoCamera_setScale(self, scale)

    def setPose(self, x, y):
        return _stagemodule.OrthoCamera_setPose(self, x, y)

    def reset(self):
        return _stagemodule.OrthoCamera_reset(self)

    def scale(self, *args):
        return _stagemodule.OrthoCamera_scale(self, *args)

    def Load(self, wf, sec):
        return _stagemodule.OrthoCamera_Load(self, wf, sec)

    def Save(self, wf, sec):
        return _stagemodule.OrthoCamera_Save(self, wf, sec)
    __swig_destroy__ = _stagemodule.delete_OrthoCamera
    __del__ = lambda self: None
OrthoCamera_swigregister = _stagemodule.OrthoCamera_swigregister
OrthoCamera_swigregister(OrthoCamera)

class WorldGui(World):
    __swig_setmethods__ = {}
    for _s in [World]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, WorldGui, name, value)
    __swig_getmethods__ = {}
    for _s in [World]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, WorldGui, name)
    __repr__ = _swig_repr

    def __init__(self, W, H, L=None):
        this = _stagemodule.new_WorldGui(W, H, L)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_WorldGui
    __del__ = lambda self: None

    def Redraw(self):
        return _stagemodule.WorldGui_Redraw(self)

    def ClockString(self):
        return _stagemodule.WorldGui_ClockString(self)

    def Update(self):
        return _stagemodule.WorldGui_Update(self)

    def Load(self, filename):
        return _stagemodule.WorldGui_Load(self, filename)

    def UnLoad(self):
        return _stagemodule.WorldGui_UnLoad(self)

    def Save(self, filename):
        return _stagemodule.WorldGui_Save(self, filename)

    def IsGUI(self):
        return _stagemodule.WorldGui_IsGUI(self)

    def RecentlySelectedModel(self):
        return _stagemodule.WorldGui_RecentlySelectedModel(self)

    def Start(self):
        return _stagemodule.WorldGui_Start(self)

    def Stop(self):
        return _stagemodule.WorldGui_Stop(self)

    def RealTimeNow(self):
        return _stagemodule.WorldGui_RealTimeNow(self)

    def DrawBoundingBoxTree(self):
        return _stagemodule.WorldGui_DrawBoundingBoxTree(self)

    def GetCanvas(self):
        return _stagemodule.WorldGui_GetCanvas(self)

    def Show(self):
        return _stagemodule.WorldGui_Show(self)

    def EnergyString(self):
        return _stagemodule.WorldGui_EnergyString(self)

    def RemoveChild(self, mod):
        return _stagemodule.WorldGui_RemoveChild(self, mod)

    def IsTopView(self):
        return _stagemodule.WorldGui_IsTopView(self)
WorldGui_swigregister = _stagemodule.WorldGui_swigregister
WorldGui_swigregister(WorldGui)

class StripPlotVis(Visualizer):
    __swig_setmethods__ = {}
    for _s in [Visualizer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, StripPlotVis, name, value)
    __swig_getmethods__ = {}
    for _s in [Visualizer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, StripPlotVis, name)
    __repr__ = _swig_repr

    def __init__(self, x, y, w, h, len, fgcolor, bgcolor, name, wfname):
        this = _stagemodule.new_StripPlotVis(x, y, w, h, len, fgcolor, bgcolor, name, wfname)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_StripPlotVis
    __del__ = lambda self: None

    def Visualize(self, mod, cam):
        return _stagemodule.StripPlotVis_Visualize(self, mod, cam)

    def AppendValue(self, value):
        return _stagemodule.StripPlotVis_AppendValue(self, value)
StripPlotVis_swigregister = _stagemodule.StripPlotVis_swigregister
StripPlotVis_swigregister(StripPlotVis)

class PowerPack(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PowerPack, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PowerPack, name)
    __repr__ = _swig_repr
    __swig_setmethods__["global_stored"] = _stagemodule.PowerPack_global_stored_set
    __swig_getmethods__["global_stored"] = _stagemodule.PowerPack_global_stored_get
    if _newclass:
        global_stored = _swig_property(_stagemodule.PowerPack_global_stored_get, _stagemodule.PowerPack_global_stored_set)
    __swig_setmethods__["global_capacity"] = _stagemodule.PowerPack_global_capacity_set
    __swig_getmethods__["global_capacity"] = _stagemodule.PowerPack_global_capacity_get
    if _newclass:
        global_capacity = _swig_property(_stagemodule.PowerPack_global_capacity_get, _stagemodule.PowerPack_global_capacity_set)
    __swig_setmethods__["global_dissipated"] = _stagemodule.PowerPack_global_dissipated_set
    __swig_getmethods__["global_dissipated"] = _stagemodule.PowerPack_global_dissipated_get
    if _newclass:
        global_dissipated = _swig_property(_stagemodule.PowerPack_global_dissipated_get, _stagemodule.PowerPack_global_dissipated_set)
    __swig_setmethods__["global_input"] = _stagemodule.PowerPack_global_input_set
    __swig_getmethods__["global_input"] = _stagemodule.PowerPack_global_input_get
    if _newclass:
        global_input = _swig_property(_stagemodule.PowerPack_global_input_get, _stagemodule.PowerPack_global_input_set)

    def __init__(self, mod):
        this = _stagemodule.new_PowerPack(mod)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_PowerPack
    __del__ = lambda self: None

    def Visualize(self, cam):
        return _stagemodule.PowerPack_Visualize(self, cam)

    def RemainingCapacity(self):
        return _stagemodule.PowerPack_RemainingCapacity(self)

    def Add(self, j):
        return _stagemodule.PowerPack_Add(self, j)

    def Subtract(self, j):
        return _stagemodule.PowerPack_Subtract(self, j)

    def TransferTo(self, dest, amount):
        return _stagemodule.PowerPack_TransferTo(self, dest, amount)

    def ProportionRemaining(self):
        return _stagemodule.PowerPack_ProportionRemaining(self)

    def Print(self, prefix):
        return _stagemodule.PowerPack_Print(self, prefix)

    def GetStored(self):
        return _stagemodule.PowerPack_GetStored(self)

    def GetCapacity(self):
        return _stagemodule.PowerPack_GetCapacity(self)

    def GetDissipated(self):
        return _stagemodule.PowerPack_GetDissipated(self)

    def SetCapacity(self, j):
        return _stagemodule.PowerPack_SetCapacity(self, j)

    def SetStored(self, j):
        return _stagemodule.PowerPack_SetStored(self, j)

    def GetCharging(self):
        return _stagemodule.PowerPack_GetCharging(self)

    def ChargeStart(self):
        return _stagemodule.PowerPack_ChargeStart(self)

    def ChargeStop(self):
        return _stagemodule.PowerPack_ChargeStop(self)

    def Dissipate(self, *args):
        return _stagemodule.PowerPack_Dissipate(self, *args)
PowerPack_swigregister = _stagemodule.PowerPack_swigregister
PowerPack_swigregister(PowerPack)

class Model(Ancestor):
    __swig_setmethods__ = {}
    for _s in [Ancestor]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Model, name, value)
    __swig_getmethods__ = {}
    for _s in [Ancestor]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Model, name)
    __repr__ = _swig_repr
    CB_FLAGDECR = _stagemodule.Model_CB_FLAGDECR
    CB_FLAGINCR = _stagemodule.Model_CB_FLAGINCR
    CB_GEOM = _stagemodule.Model_CB_GEOM
    CB_INIT = _stagemodule.Model_CB_INIT
    CB_LOAD = _stagemodule.Model_CB_LOAD
    CB_PARENT = _stagemodule.Model_CB_PARENT
    CB_POSE = _stagemodule.Model_CB_POSE
    CB_SAVE = _stagemodule.Model_CB_SAVE
    CB_SHUTDOWN = _stagemodule.Model_CB_SHUTDOWN
    CB_STARTUP = _stagemodule.Model_CB_STARTUP
    CB_UPDATE = _stagemodule.Model_CB_UPDATE
    CB_VELOCITY = _stagemodule.Model_CB_VELOCITY
    __CB_TYPE_COUNT = _stagemodule.Model___CB_TYPE_COUNT

    def SetToken(self, str):
        return _stagemodule.Model_SetToken(self, str)

    def GetModelType(self):
        return _stagemodule.Model_GetModelType(self)

    def GetSayString(self):
        return _stagemodule.Model_GetSayString(self)

    def GetChild(self, name):
        return _stagemodule.Model_GetChild(self, name)

    def GetInterval(self):
        return _stagemodule.Model_GetInterval(self)
    __swig_setmethods__["vis"] = _stagemodule.Model_vis_set
    __swig_getmethods__["vis"] = _stagemodule.Model_vis_get
    if _newclass:
        vis = _swig_property(_stagemodule.Model_vis_get, _stagemodule.Model_vis_set)

    def GetUpdateInterval(self):
        return _stagemodule.Model_GetUpdateInterval(self)

    def GetEnergyInterval(self):
        return _stagemodule.Model_GetEnergyInterval(self)

    def Rasterize(self, data, width, height, cellwidth, cellheight):
        return _stagemodule.Model_Rasterize(self, data, width, height, cellwidth, cellheight)

    def PushColor(self, *args):
        return _stagemodule.Model_PushColor(self, *args)

    def PopColor(self):
        return _stagemodule.Model_PopColor(self)

    def FindPowerPack(self):
        return _stagemodule.Model_FindPowerPack(self)

    def PlaceInFreeSpace(self, xmin, xmax, ymin, ymax):
        return _stagemodule.Model_PlaceInFreeSpace(self, xmin, xmax, ymin, ymax)

    def PoseString(self):
        return _stagemodule.Model_PoseString(self)
    __swig_getmethods__["LookupId"] = lambda x: _stagemodule.Model_LookupId
    if _newclass:
        LookupId = staticmethod(_stagemodule.Model_LookupId)
    __swig_destroy__ = _stagemodule.delete_Model
    __del__ = lambda self: None

    def __init__(self, *args):
        this = _stagemodule.new_Model(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Say(self, str):
        return _stagemodule.Model_Say(self, str)

    def AddVisualizer(self, custom_visual, on_by_default):
        return _stagemodule.Model_AddVisualizer(self, custom_visual, on_by_default)

    def RemoveVisualizer(self, custom_visual):
        return _stagemodule.Model_RemoveVisualizer(self, custom_visual)

    def BecomeParentOf(self, child):
        return _stagemodule.Model_BecomeParentOf(self, child)

    def SetWorldfile(self, wf, wf_entity):
        return _stagemodule.Model_SetWorldfile(self, wf, wf_entity)

    def Load(self, *args):
        return _stagemodule.Model_Load(self, *args)

    def Save(self):
        return _stagemodule.Model_Save(self)

    def InitControllers(self):
        return _stagemodule.Model_InitControllers(self)

    def AddFlag(self, flag):
        return _stagemodule.Model_AddFlag(self, flag)

    def RemoveFlag(self, flag):
        return _stagemodule.Model_RemoveFlag(self, flag)

    def PushFlag(self, flag):
        return _stagemodule.Model_PushFlag(self, flag)

    def PopFlag(self):
        return _stagemodule.Model_PopFlag(self)

    def GetFlagCount(self):
        return _stagemodule.Model_GetFlagCount(self)

    def Disable(self):
        return _stagemodule.Model_Disable(self)

    def Enable(self):
        return _stagemodule.Model_Enable(self)

    def LoadControllerModule(self, lib):
        return _stagemodule.Model_LoadControllerModule(self, lib)

    def NeedRedraw(self):
        return _stagemodule.Model_NeedRedraw(self)

    def Redraw(self):
        return _stagemodule.Model_Redraw(self)

    def LoadBlock(self, wf, entity):
        return _stagemodule.Model_LoadBlock(self, wf, entity)

    def AddBlockRect(self, x, y, dx, dy, dz):
        return _stagemodule.Model_AddBlockRect(self, x, y, dx, dy, dz)

    def ClearBlocks(self):
        return _stagemodule.Model_ClearBlocks(self)

    def Parent(self):
        return _stagemodule.Model_Parent(self)

    def GetWorld(self):
        return _stagemodule.Model_GetWorld(self)

    def Root(self):
        return _stagemodule.Model_Root(self)

    def IsAntecedent(self, testmod):
        return _stagemodule.Model_IsAntecedent(self, testmod)

    def IsDescendent(self, testmod):
        return _stagemodule.Model_IsDescendent(self, testmod)

    def IsRelated(self, testmod):
        return _stagemodule.Model_IsRelated(self, testmod)

    def GetGlobalPose(self):
        return _stagemodule.Model_GetGlobalPose(self)

    def Subscribe(self):
        return _stagemodule.Model_Subscribe(self)

    def Unsubscribe(self):
        return _stagemodule.Model_Unsubscribe(self)

    def SetGlobalPose(self, gpose):
        return _stagemodule.Model_SetGlobalPose(self, gpose)

    def SetPose(self, pose):
        return _stagemodule.Model_SetPose(self, pose)

    def AddToPose(self, *args):
        return _stagemodule.Model_AddToPose(self, *args)

    def SetGeom(self, src):
        return _stagemodule.Model_SetGeom(self, src)

    def SetFiducialReturn(self, fid):
        return _stagemodule.Model_SetFiducialReturn(self, fid)

    def GetFiducialReturn(self):
        return _stagemodule.Model_GetFiducialReturn(self)

    def SetFiducialKey(self, key):
        return _stagemodule.Model_SetFiducialKey(self, key)

    def GetColor(self):
        return _stagemodule.Model_GetColor(self)

    def GetId(self):
        return _stagemodule.Model_GetId(self)

    def GetTotalMass(self):
        return _stagemodule.Model_GetTotalMass(self)

    def GetMassOfChildren(self):
        return _stagemodule.Model_GetMassOfChildren(self)

    def SetParent(self, newparent):
        return _stagemodule.Model_SetParent(self, newparent)

    def GetGeom(self):
        return _stagemodule.Model_GetGeom(self)

    def GetPose(self):
        return _stagemodule.Model_GetPose(self)

    def SetColor(self, col):
        return _stagemodule.Model_SetColor(self, col)

    def SetMass(self, mass):
        return _stagemodule.Model_SetMass(self, mass)

    def SetStall(self, stall):
        return _stagemodule.Model_SetStall(self, stall)

    def SetGravityReturn(self, val):
        return _stagemodule.Model_SetGravityReturn(self, val)

    def SetGripperReturn(self, val):
        return _stagemodule.Model_SetGripperReturn(self, val)

    def SetStickyReturn(self, val):
        return _stagemodule.Model_SetStickyReturn(self, val)

    def SetObstacleReturn(self, val):
        return _stagemodule.Model_SetObstacleReturn(self, val)

    def SetBlobReturn(self, val):
        return _stagemodule.Model_SetBlobReturn(self, val)

    def SetRangerReturn(self, *args):
        return _stagemodule.Model_SetRangerReturn(self, *args)

    def SetBoundary(self, val):
        return _stagemodule.Model_SetBoundary(self, val)

    def SetGuiNose(self, val):
        return _stagemodule.Model_SetGuiNose(self, val)

    def SetGuiMove(self, val):
        return _stagemodule.Model_SetGuiMove(self, val)

    def SetGuiGrid(self, val):
        return _stagemodule.Model_SetGuiGrid(self, val)

    def SetGuiOutline(self, val):
        return _stagemodule.Model_SetGuiOutline(self, val)

    def SetWatts(self, watts):
        return _stagemodule.Model_SetWatts(self, watts)

    def SetMapResolution(self, res):
        return _stagemodule.Model_SetMapResolution(self, res)

    def SetFriction(self, friction):
        return _stagemodule.Model_SetFriction(self, friction)

    def DataIsFresh(self):
        return _stagemodule.Model_DataIsFresh(self)

    def AddCallback(self, type, cb, user):
        return _stagemodule.Model_AddCallback(self, type, cb, user)

    def RemoveCallback(self, type, callback):
        return _stagemodule.Model_RemoveCallback(self, type, callback)

    def CallCallbacks(self, type):
        return _stagemodule.Model_CallCallbacks(self, type)

    def Print(self, prefix):
        return _stagemodule.Model_Print(self, prefix)

    def PrintWithPose(self):
        return _stagemodule.Model_PrintWithPose(self)

    def GlobalToLocal(self, pose):
        return _stagemodule.Model_GlobalToLocal(self, pose)

    def LocalToPixels(self, local):
        return _stagemodule.Model_LocalToPixels(self, local)

    def LocalToGlobal(self, *args):
        return _stagemodule.Model_LocalToGlobal(self, *args)

    def GetUnsubscribedModelOfType(self, type):
        return _stagemodule.Model_GetUnsubscribedModelOfType(self, type)

    def GetUnusedModelOfType(self, type):
        return _stagemodule.Model_GetUnusedModelOfType(self, type)

    def Stalled(self):
        return _stagemodule.Model_Stalled(self)

    def GetSubscriptionCount(self):
        return _stagemodule.Model_GetSubscriptionCount(self)

    def HasSubscribers(self):
        return _stagemodule.Model_HasSubscribers(self)
    __swig_setmethods__["name_map"] = _stagemodule.Model_name_map_set
    __swig_getmethods__["name_map"] = _stagemodule.Model_name_map_get
    if _newclass:
        name_map = _swig_property(_stagemodule.Model_name_map_get, _stagemodule.Model_name_map_set)
Model_swigregister = _stagemodule.Model_swigregister
Model_swigregister(Model)

def Model_LookupId(id):
    return _stagemodule.Model_LookupId(id)
Model_LookupId = _stagemodule.Model_LookupId

class ModelBlobfinder(Model):
    __swig_setmethods__ = {}
    for _s in [Model]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModelBlobfinder, name, value)
    __swig_getmethods__ = {}
    for _s in [Model]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ModelBlobfinder, name)
    __repr__ = _swig_repr
    __swig_setmethods__["vis"] = _stagemodule.ModelBlobfinder_vis_set
    __swig_getmethods__["vis"] = _stagemodule.ModelBlobfinder_vis_get
    if _newclass:
        vis = _swig_property(_stagemodule.ModelBlobfinder_vis_get, _stagemodule.ModelBlobfinder_vis_set)
    __swig_setmethods__["fov"] = _stagemodule.ModelBlobfinder_fov_set
    __swig_getmethods__["fov"] = _stagemodule.ModelBlobfinder_fov_get
    if _newclass:
        fov = _swig_property(_stagemodule.ModelBlobfinder_fov_get, _stagemodule.ModelBlobfinder_fov_set)
    __swig_setmethods__["pan"] = _stagemodule.ModelBlobfinder_pan_set
    __swig_getmethods__["pan"] = _stagemodule.ModelBlobfinder_pan_get
    if _newclass:
        pan = _swig_property(_stagemodule.ModelBlobfinder_pan_get, _stagemodule.ModelBlobfinder_pan_set)
    __swig_setmethods__["range"] = _stagemodule.ModelBlobfinder_range_set
    __swig_getmethods__["range"] = _stagemodule.ModelBlobfinder_range_get
    if _newclass:
        range = _swig_property(_stagemodule.ModelBlobfinder_range_get, _stagemodule.ModelBlobfinder_range_set)
    __swig_setmethods__["scan_height"] = _stagemodule.ModelBlobfinder_scan_height_set
    __swig_getmethods__["scan_height"] = _stagemodule.ModelBlobfinder_scan_height_get
    if _newclass:
        scan_height = _swig_property(_stagemodule.ModelBlobfinder_scan_height_get, _stagemodule.ModelBlobfinder_scan_height_set)
    __swig_setmethods__["scan_width"] = _stagemodule.ModelBlobfinder_scan_width_set
    __swig_getmethods__["scan_width"] = _stagemodule.ModelBlobfinder_scan_width_get
    if _newclass:
        scan_width = _swig_property(_stagemodule.ModelBlobfinder_scan_width_get, _stagemodule.ModelBlobfinder_scan_width_set)

    def __init__(self, world, parent, type):
        this = _stagemodule.new_ModelBlobfinder(world, parent, type)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_ModelBlobfinder
    __del__ = lambda self: None

    def Startup(self):
        return _stagemodule.ModelBlobfinder_Startup(self)

    def Shutdown(self):
        return _stagemodule.ModelBlobfinder_Shutdown(self)

    def Update(self):
        return _stagemodule.ModelBlobfinder_Update(self)

    def Load(self):
        return _stagemodule.ModelBlobfinder_Load(self)

    def GetBlobs(self):
        return _stagemodule.ModelBlobfinder_GetBlobs(self)

    def GetBlobsMutable(self):
        return _stagemodule.ModelBlobfinder_GetBlobsMutable(self)

    def AddColor(self, col):
        return _stagemodule.ModelBlobfinder_AddColor(self, col)

    def RemoveColor(self, col):
        return _stagemodule.ModelBlobfinder_RemoveColor(self, col)

    def RemoveAllColors(self):
        return _stagemodule.ModelBlobfinder_RemoveAllColors(self)
ModelBlobfinder_swigregister = _stagemodule.ModelBlobfinder_swigregister
ModelBlobfinder_swigregister(ModelBlobfinder)

class ModelLightIndicator(Model):
    __swig_setmethods__ = {}
    for _s in [Model]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModelLightIndicator, name, value)
    __swig_getmethods__ = {}
    for _s in [Model]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ModelLightIndicator, name)
    __repr__ = _swig_repr

    def __init__(self, world, parent, type):
        this = _stagemodule.new_ModelLightIndicator(world, parent, type)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_ModelLightIndicator
    __del__ = lambda self: None

    def SetState(self, isOn):
        return _stagemodule.ModelLightIndicator_SetState(self, isOn)
ModelLightIndicator_swigregister = _stagemodule.ModelLightIndicator_swigregister
ModelLightIndicator_swigregister(ModelLightIndicator)

class ModelGripper(Model):
    __swig_setmethods__ = {}
    for _s in [Model]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModelGripper, name, value)
    __swig_getmethods__ = {}
    for _s in [Model]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ModelGripper, name)
    __repr__ = _swig_repr
    PADDLE_OPEN = _stagemodule.ModelGripper_PADDLE_OPEN
    PADDLE_CLOSED = _stagemodule.ModelGripper_PADDLE_CLOSED
    PADDLE_OPENING = _stagemodule.ModelGripper_PADDLE_OPENING
    PADDLE_CLOSING = _stagemodule.ModelGripper_PADDLE_CLOSING
    LIFT_DOWN = _stagemodule.ModelGripper_LIFT_DOWN
    LIFT_UP = _stagemodule.ModelGripper_LIFT_UP
    LIFT_UPPING = _stagemodule.ModelGripper_LIFT_UPPING
    LIFT_DOWNING = _stagemodule.ModelGripper_LIFT_DOWNING
    CMD_NOOP = _stagemodule.ModelGripper_CMD_NOOP
    CMD_OPEN = _stagemodule.ModelGripper_CMD_OPEN
    CMD_CLOSE = _stagemodule.ModelGripper_CMD_CLOSE
    CMD_UP = _stagemodule.ModelGripper_CMD_UP
    CMD_DOWN = _stagemodule.ModelGripper_CMD_DOWN

    def __init__(self, world, parent, type):
        this = _stagemodule.new_ModelGripper(world, parent, type)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_ModelGripper
    __del__ = lambda self: None

    def Load(self):
        return _stagemodule.ModelGripper_Load(self)

    def Save(self):
        return _stagemodule.ModelGripper_Save(self)

    def SetConfig(self, newcfg):
        return _stagemodule.ModelGripper_SetConfig(self, newcfg)

    def GetConfig(self):
        return _stagemodule.ModelGripper_GetConfig(self)

    def SetCommand(self, cmd):
        return _stagemodule.ModelGripper_SetCommand(self, cmd)

    def CommandClose(self):
        return _stagemodule.ModelGripper_CommandClose(self)

    def CommandOpen(self):
        return _stagemodule.ModelGripper_CommandOpen(self)

    def CommandUp(self):
        return _stagemodule.ModelGripper_CommandUp(self)

    def CommandDown(self):
        return _stagemodule.ModelGripper_CommandDown(self)
ModelGripper_swigregister = _stagemodule.ModelGripper_swigregister
ModelGripper_swigregister(ModelGripper)
ModelGripper.size = _stagemodule.cvar.ModelGripper_size

class ModelFiducial(Model):
    __swig_setmethods__ = {}
    for _s in [Model]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModelFiducial, name, value)
    __swig_getmethods__ = {}
    for _s in [Model]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ModelFiducial, name)
    __repr__ = _swig_repr

    def __init__(self, world, parent, type):
        this = _stagemodule.new_ModelFiducial(world, parent, type)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_ModelFiducial
    __del__ = lambda self: None

    def Load(self):
        return _stagemodule.ModelFiducial_Load(self)

    def Shutdown(self):
        return _stagemodule.ModelFiducial_Shutdown(self)
    __swig_setmethods__["max_range_anon"] = _stagemodule.ModelFiducial_max_range_anon_set
    __swig_getmethods__["max_range_anon"] = _stagemodule.ModelFiducial_max_range_anon_get
    if _newclass:
        max_range_anon = _swig_property(_stagemodule.ModelFiducial_max_range_anon_get, _stagemodule.ModelFiducial_max_range_anon_set)
    __swig_setmethods__["max_range_id"] = _stagemodule.ModelFiducial_max_range_id_set
    __swig_getmethods__["max_range_id"] = _stagemodule.ModelFiducial_max_range_id_get
    if _newclass:
        max_range_id = _swig_property(_stagemodule.ModelFiducial_max_range_id_get, _stagemodule.ModelFiducial_max_range_id_set)
    __swig_setmethods__["min_range"] = _stagemodule.ModelFiducial_min_range_set
    __swig_getmethods__["min_range"] = _stagemodule.ModelFiducial_min_range_get
    if _newclass:
        min_range = _swig_property(_stagemodule.ModelFiducial_min_range_get, _stagemodule.ModelFiducial_min_range_set)
    __swig_setmethods__["fov"] = _stagemodule.ModelFiducial_fov_set
    __swig_getmethods__["fov"] = _stagemodule.ModelFiducial_fov_get
    if _newclass:
        fov = _swig_property(_stagemodule.ModelFiducial_fov_get, _stagemodule.ModelFiducial_fov_set)
    __swig_setmethods__["heading"] = _stagemodule.ModelFiducial_heading_set
    __swig_getmethods__["heading"] = _stagemodule.ModelFiducial_heading_get
    if _newclass:
        heading = _swig_property(_stagemodule.ModelFiducial_heading_get, _stagemodule.ModelFiducial_heading_set)
    __swig_setmethods__["key"] = _stagemodule.ModelFiducial_key_set
    __swig_getmethods__["key"] = _stagemodule.ModelFiducial_key_get
    if _newclass:
        key = _swig_property(_stagemodule.ModelFiducial_key_get, _stagemodule.ModelFiducial_key_set)
    __swig_setmethods__["ignore_zloc"] = _stagemodule.ModelFiducial_ignore_zloc_set
    __swig_getmethods__["ignore_zloc"] = _stagemodule.ModelFiducial_ignore_zloc_get
    if _newclass:
        ignore_zloc = _swig_property(_stagemodule.ModelFiducial_ignore_zloc_get, _stagemodule.ModelFiducial_ignore_zloc_set)

    def GetFiducials(self, *args):
        return _stagemodule.ModelFiducial_GetFiducials(self, *args)
ModelFiducial_swigregister = _stagemodule.ModelFiducial_swigregister
ModelFiducial_swigregister(ModelFiducial)

class ModelRanger(Model):
    __swig_setmethods__ = {}
    for _s in [Model]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModelRanger, name, value)
    __swig_getmethods__ = {}
    for _s in [Model]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ModelRanger, name)
    __repr__ = _swig_repr

    def __init__(self, world, parent, type):
        this = _stagemodule.new_ModelRanger(world, parent, type)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_ModelRanger
    __del__ = lambda self: None

    def Print(self, prefix):
        return _stagemodule.ModelRanger_Print(self, prefix)
    __swig_setmethods__["vis"] = _stagemodule.ModelRanger_vis_set
    __swig_getmethods__["vis"] = _stagemodule.ModelRanger_vis_get
    if _newclass:
        vis = _swig_property(_stagemodule.ModelRanger_vis_get, _stagemodule.ModelRanger_vis_set)

    def GetSensors(self):
        return _stagemodule.ModelRanger_GetSensors(self)

    def GetSensorsMutable(self):
        return _stagemodule.ModelRanger_GetSensorsMutable(self)

    def LoadSensor(self, wf, entity):
        return _stagemodule.ModelRanger_LoadSensor(self, wf, entity)
ModelRanger_swigregister = _stagemodule.ModelRanger_swigregister
ModelRanger_swigregister(ModelRanger)

class ModelBlinkenlight(Model):
    __swig_setmethods__ = {}
    for _s in [Model]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModelBlinkenlight, name, value)
    __swig_getmethods__ = {}
    for _s in [Model]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ModelBlinkenlight, name)
    __repr__ = _swig_repr

    def __init__(self, world, parent, type):
        this = _stagemodule.new_ModelBlinkenlight(world, parent, type)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_ModelBlinkenlight
    __del__ = lambda self: None

    def Load(self):
        return _stagemodule.ModelBlinkenlight_Load(self)

    def Update(self):
        return _stagemodule.ModelBlinkenlight_Update(self)

    def DataVisualize(self, cam):
        return _stagemodule.ModelBlinkenlight_DataVisualize(self, cam)
ModelBlinkenlight_swigregister = _stagemodule.ModelBlinkenlight_swigregister
ModelBlinkenlight_swigregister(ModelBlinkenlight)

class ModelCamera(Model):
    __swig_setmethods__ = {}
    for _s in [Model]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModelCamera, name, value)
    __swig_getmethods__ = {}
    for _s in [Model]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ModelCamera, name)
    __repr__ = _swig_repr

    def __init__(self, world, parent, type):
        this = _stagemodule.new_ModelCamera(world, parent, type)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_ModelCamera
    __del__ = lambda self: None

    def Load(self):
        return _stagemodule.ModelCamera_Load(self)

    def Update(self):
        return _stagemodule.ModelCamera_Update(self)

    def DataVisualize(self, cam):
        return _stagemodule.ModelCamera_DataVisualize(self, cam)

    def getWidth(self):
        return _stagemodule.ModelCamera_getWidth(self)

    def getHeight(self):
        return _stagemodule.ModelCamera_getHeight(self)

    def getCamera(self):
        return _stagemodule.ModelCamera_getCamera(self)

    def FrameDepth(self):
        return _stagemodule.ModelCamera_FrameDepth(self)

    def FrameColor(self):
        return _stagemodule.ModelCamera_FrameColor(self)

    def setPitch(self, pitch):
        return _stagemodule.ModelCamera_setPitch(self, pitch)

    def setYaw(self, yaw):
        return _stagemodule.ModelCamera_setYaw(self, yaw)
ModelCamera_swigregister = _stagemodule.ModelCamera_swigregister
ModelCamera_swigregister(ModelCamera)

class ModelPosition(Model):
    __swig_setmethods__ = {}
    for _s in [Model]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModelPosition, name, value)
    __swig_getmethods__ = {}
    for _s in [Model]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ModelPosition, name)
    __repr__ = _swig_repr
    CONTROL_ACCELERATION = _stagemodule.ModelPosition_CONTROL_ACCELERATION
    CONTROL_VELOCITY = _stagemodule.ModelPosition_CONTROL_VELOCITY
    CONTROL_POSITION = _stagemodule.ModelPosition_CONTROL_POSITION
    LOCALIZATION_GPS = _stagemodule.ModelPosition_LOCALIZATION_GPS
    LOCALIZATION_ODOM = _stagemodule.ModelPosition_LOCALIZATION_ODOM
    DRIVE_DIFFERENTIAL = _stagemodule.ModelPosition_DRIVE_DIFFERENTIAL
    DRIVE_OMNI = _stagemodule.ModelPosition_DRIVE_OMNI
    DRIVE_CAR = _stagemodule.ModelPosition_DRIVE_CAR
    __swig_setmethods__["acceleration_bounds"] = _stagemodule.ModelPosition_acceleration_bounds_set
    __swig_getmethods__["acceleration_bounds"] = _stagemodule.ModelPosition_acceleration_bounds_get
    if _newclass:
        acceleration_bounds = _swig_property(_stagemodule.ModelPosition_acceleration_bounds_get, _stagemodule.ModelPosition_acceleration_bounds_set)
    __swig_setmethods__["velocity_bounds"] = _stagemodule.ModelPosition_velocity_bounds_set
    __swig_getmethods__["velocity_bounds"] = _stagemodule.ModelPosition_velocity_bounds_get
    if _newclass:
        velocity_bounds = _swig_property(_stagemodule.ModelPosition_velocity_bounds_get, _stagemodule.ModelPosition_velocity_bounds_set)

    def __init__(self, world, parent, type):
        this = _stagemodule.new_ModelPosition(world, parent, type)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_ModelPosition
    __del__ = lambda self: None

    def GetVelocity(self):
        return _stagemodule.ModelPosition_GetVelocity(self)

    def SetVelocity(self, val):
        return _stagemodule.ModelPosition_SetVelocity(self, val)

    def GetGlobalVelocity(self):
        return _stagemodule.ModelPosition_GetGlobalVelocity(self)

    def SetGlobalVelocity(self, gvel):
        return _stagemodule.ModelPosition_SetGlobalVelocity(self, gvel)
    __swig_setmethods__["waypoints"] = _stagemodule.ModelPosition_waypoints_set
    __swig_getmethods__["waypoints"] = _stagemodule.ModelPosition_waypoints_get
    if _newclass:
        waypoints = _swig_property(_stagemodule.ModelPosition_waypoints_get, _stagemodule.ModelPosition_waypoints_set)
    __swig_setmethods__["wpvis"] = _stagemodule.ModelPosition_wpvis_set
    __swig_getmethods__["wpvis"] = _stagemodule.ModelPosition_wpvis_get
    if _newclass:
        wpvis = _swig_property(_stagemodule.ModelPosition_wpvis_get, _stagemodule.ModelPosition_wpvis_set)
    __swig_setmethods__["posevis"] = _stagemodule.ModelPosition_posevis_set
    __swig_getmethods__["posevis"] = _stagemodule.ModelPosition_posevis_get
    if _newclass:
        posevis = _swig_property(_stagemodule.ModelPosition_posevis_get, _stagemodule.ModelPosition_posevis_set)

    def SetOdom(self, odom):
        return _stagemodule.ModelPosition_SetOdom(self, odom)

    def SetXSpeed(self, x):
        return _stagemodule.ModelPosition_SetXSpeed(self, x)

    def SetYSpeed(self, y):
        return _stagemodule.ModelPosition_SetYSpeed(self, y)

    def SetZSpeed(self, z):
        return _stagemodule.ModelPosition_SetZSpeed(self, z)

    def SetTurnSpeed(self, a):
        return _stagemodule.ModelPosition_SetTurnSpeed(self, a)

    def SetSpeed(self, *args):
        return _stagemodule.ModelPosition_SetSpeed(self, *args)

    def Stop(self):
        return _stagemodule.ModelPosition_Stop(self)

    def GoTo(self, *args):
        return _stagemodule.ModelPosition_GoTo(self, *args)

    def SetAcceleration(self, x, y, a):
        return _stagemodule.ModelPosition_SetAcceleration(self, x, y, a)
    __swig_setmethods__["est_pose"] = _stagemodule.ModelPosition_est_pose_set
    __swig_getmethods__["est_pose"] = _stagemodule.ModelPosition_est_pose_get
    if _newclass:
        est_pose = _swig_property(_stagemodule.ModelPosition_est_pose_get, _stagemodule.ModelPosition_est_pose_set)
    __swig_setmethods__["est_pose_error"] = _stagemodule.ModelPosition_est_pose_error_set
    __swig_getmethods__["est_pose_error"] = _stagemodule.ModelPosition_est_pose_error_get
    if _newclass:
        est_pose_error = _swig_property(_stagemodule.ModelPosition_est_pose_error_get, _stagemodule.ModelPosition_est_pose_error_set)
    __swig_setmethods__["est_origin"] = _stagemodule.ModelPosition_est_origin_set
    __swig_getmethods__["est_origin"] = _stagemodule.ModelPosition_est_origin_get
    if _newclass:
        est_origin = _swig_property(_stagemodule.ModelPosition_est_origin_get, _stagemodule.ModelPosition_est_origin_set)
ModelPosition_swigregister = _stagemodule.ModelPosition_swigregister
ModelPosition_swigregister(ModelPosition)

class ModelActuator(Model):
    __swig_setmethods__ = {}
    for _s in [Model]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModelActuator, name, value)
    __swig_getmethods__ = {}
    for _s in [Model]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ModelActuator, name)
    __repr__ = _swig_repr
    CONTROL_VELOCITY = _stagemodule.ModelActuator_CONTROL_VELOCITY
    CONTROL_POSITION = _stagemodule.ModelActuator_CONTROL_POSITION
    TYPE_LINEAR = _stagemodule.ModelActuator_TYPE_LINEAR
    TYPE_ROTATIONAL = _stagemodule.ModelActuator_TYPE_ROTATIONAL

    def __init__(self, world, parent, type):
        this = _stagemodule.new_ModelActuator(world, parent, type)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _stagemodule.delete_ModelActuator
    __del__ = lambda self: None

    def Startup(self):
        return _stagemodule.ModelActuator_Startup(self)

    def Shutdown(self):
        return _stagemodule.ModelActuator_Shutdown(self)

    def Update(self):
        return _stagemodule.ModelActuator_Update(self)

    def Load(self):
        return _stagemodule.ModelActuator_Load(self)

    def SetSpeed(self, speed):
        return _stagemodule.ModelActuator_SetSpeed(self, speed)

    def GetSpeed(self):
        return _stagemodule.ModelActuator_GetSpeed(self)

    def GoTo(self, pose):
        return _stagemodule.ModelActuator_GoTo(self, pose)

    def GetPosition(self):
        return _stagemodule.ModelActuator_GetPosition(self)

    def GetMaxPosition(self):
        return _stagemodule.ModelActuator_GetMaxPosition(self)

    def GetMinPosition(self):
        return _stagemodule.ModelActuator_GetMinPosition(self)

    def GetType(self):
        return _stagemodule.ModelActuator_GetType(self)

    def GetAxis(self):
        return _stagemodule.ModelActuator_GetAxis(self)
ModelActuator_swigregister = _stagemodule.ModelActuator_swigregister
ModelActuator_swigregister(ModelActuator)

# This file is compatible with both classic and new-style classes.


